/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsDriveInfo {
  name: string
  path: string
  capacity: string
  freeSpace: string
  fileSystem: string
  isPrimary: boolean
  type: string
}
export declare function listDrives(): Array<JsDriveInfo>
export declare function readSectors(drivePath: string, offset: number, size: number): Buffer
